name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build extension
      run: npm run build
    
    - name: Create ZIP file
      run: |
        cd dist
        zip -r ../braze-autocomplete-extension-v${{ github.event.inputs.version }}.zip .
        cd ..
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: braze-autocomplete-extension-v${{ github.event.inputs.version }}
        path: braze-autocomplete-extension-v${{ github.event.inputs.version }}.zip
        retention-days: 30
